---
title: "Punkt 3"
output: html_notebook
---


```{r}
suppressPackageStartupMessages({
library(PxWebApiData)
library(dplyr)
library(tidyverse)
library(lubridate)
library(REAT)
})
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```



I denne oppgaven skal vi finne sysselsetting i de ulike næringene, etter arbeidsstedskommune.

```{r}
knr <- c("1106", "1135", "1145", "1146", "1149", "1151", "1160")
```


```{r}
Haug_bo_raw <- ApiData(
  url = "07984",
  Region = list("vs:KommunerS", knr), 
  NACE2007 = TRUE,
  Kjonn = "0",
  ContentsCode = "Sysselsatte",
  Tid = c(as.character(2008:2020)),
  Alder = c("15-74", "55-66", "67-74"),
  makeNAstatus = FALSE
)
```



```{r}
Haug_bo <- Haug_bo_raw$`07984: Sysselsatte per 4. kvartal, etter region, næring (SN2007), kjønn, alder, statistikkvariabel og år` %>% 
  tibble() %>% 
  rename(
    Knr = region,
    Aar = år,
    Naering = `næring (SN2007)`
  )
```

```{r}
names(Haug_bo_raw)[1] <- "desc4"
```

```{r}
Haug_bo <- Haug_bo %>% 
  mutate(knavn = Haug_bo_raw$Knr)
```

```{r}
Haug_bo <- Haug_bo %>% 
  pivot_wider(
    names_from = c(Knr),
    values_from = value)
```


```{r}
Haug_bo = mutate(Haug_bo, tot_h = Haugesund+Sauda+Bokn+Tysvær+Karmøy+Utsira+Vindafjord)
```

# Sunnhordaland

```{r}
knr_sunn <- c("1211", "1216",
         "1219", "1221", "1222", "1223", "1224", "1228", "1231")
```

```{r}
Sunn_bo_raw <- ApiData(
  url = "07984",
  Region = list("vs:KommunerS", knr_sunn), 
  NACE2007 = TRUE,
  Kjonn = "0",
  ContentsCode = "Sysselsatte",
  Tid = c(as.character(2008:2020)),
  Alder = c("15-74", "55-66", "67-74"),
  makeNAstatus = FALSE
)
```


```{r}
Sunn_bo <- Sunn_bo_raw$`07984: Sysselsatte per 4. kvartal, etter region, næring (SN2007), kjønn, alder, statistikkvariabel og år` %>% 
  tibble() %>% 
  rename(
    Knr = region, 
    Naering = `næring (SN2007)`,
    Aar = år
  )
```

```{r}
names(Sunn_bo_raw)[[1]]<-"desc5"
```

```{r}
Sunn_bo <- Sunn_bo %>% 
  mutate(knavn = Sunn_bo_raw$Knr)
```

```{r}
Sunn_bo <- Sunn_bo %>% 
  pivot_wider(
    names_from = Knr,
    values_from = value)
```

```{r}
names(Sunn_bo)[[6]] <- "Etne"
names(Sunn_bo)[[7]] <- "Sveio"
names(Sunn_bo)[[8]] <- "Boemlo"
names(Sunn_bo)[[9]] <- "Stord"
names(Sunn_bo)[[10]] <- "Fitjar"
names(Sunn_bo)[[11]] <- "Tysnes"
names(Sunn_bo)[[12]] <- "Kvinnherad"
names(Sunn_bo)[[13]] <- "Odda"
names(Sunn_bo)[[14]] <- "Ullensvang"
```


```{r}
Sunn_bo = mutate(Sunn_bo, tot_s = Etne + Sveio + Boemlo+ Stord+ Fitjar+ Tysnes+ Kvinnherad + Odda + Ullensvang)
```


# Totalt anasatte i hver næring for Haugalandet

```{r}
Haug_bo %>% 
  ggplot(mapping = aes(x = tot_h, y = Naering, (angle=0))) +
   scale_fill_distiller(palette = "Dark2") +
   geom_line(aes(group = Naering, colour = Naering)) +
   scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
   geom_hline(yintercept = 0) +
   labs(title = "Haugalandet", x = "Totalt ansatte", y = "Antall ansatte i  \n alle næringer") +
   theme(axis.title.y = element_text(angle=0))+
   theme(legend.position = 'bottom')
```


# Totalt anasatte i hver næring for Sunnhordaland


```{r}
 Sunn_bo %>% 
  ggplot(mapping = aes(x = tot_s, y = Naering, (angle=0))) +
   scale_fill_distiller(palette = "Dark2") +
   geom_line(aes(group = Naering, colour = Naering)) +
   scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
   geom_hline(yintercept = 0) +
   labs(title = "Sunnhordaland", x = "Totalt ansatte", y = "Antall ansatte i  \n alle næringer") +
   theme(axis.title.y = element_text(angle=0))+
   theme(legend.position = 'bottom')
```






