---
title: "Shift Share Analyse"
output: html_notebook
---

<<<<<<< HEAD
```{r}
library(ggplot2)
```



=======
>>>>>>> 0a7b71f3aefa1d9ad3e4f9d251ff60b16819dabc
```{r}
library(readxl)
Tab_shift_share <- read_excel("Data/Tab_shift_share.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric"))
View(Tab_shift_share)
```

```{r}
Tab_shift_share %>%
<<<<<<< HEAD
  select(År, Region, MIX, DIF, Sum) %>%
  filter(År %in%c( "2000-2005", "2005-2010", "2010-2015", "2015-2020")
  )%>%
  ggplot(mapping = aes(x = År, y = MIX, sec_axis(DIF), colour = Region)) +
=======
  select(År, Region, MIX) %>%
  filter(År %in%c( "2005", "2010", "2015", "2020"))%>%
  ggplot(mapping = aes(x = År, y = MIX, colour = Region)) +
>>>>>>> 0a7b71f3aefa1d9ad3e4f9d251ff60b16819dabc
  geom_line(aes(group = Region), lwd = 0.6) +
  theme(legend.position = 'bottom')+
  xlab("År") +
  ylab("Mix") +
  labs(colour = "Region")
```

```{r}
Tab_shift_share %>%
  select(År, Region, DIF) %>%
  filter(År %in%c( "2005", "2010", "2015", "2020"))%>%
  ggplot(mapping = aes(x = År, y = DIF, colour = Region)) +
  geom_line(aes(group = Region), lwd = 0.6) +
  theme(legend.position = 'bottom')+
  xlab("År") +
  ylab("DIF") +
  labs(colour = "Region")
```





