---
title: "ApiData12"
output: html_notebook
---

```{r setup}
suppressPackageStartupMessages({
library(tidyverse)
library(lubridate)
library(PxWebApiData)
})
```

# ApiData12

Siste versjon av PxWebApiData() (v. 0.7) ser ut til å ha fått en ny funksjon ApiData12() som kan være av interesse. Denne returnerer en kombinasjon av de to listene som den vanlige ApiData() gir. Man kan derfor direkte hente ut de variablene man måtte ønske uten å styre med de to listene, som synes å være opphavet til allverdens forvirring.

```{r}
knr <- as.character(c(1106, 1135, 1145, 1146, 1149, 1151, 1154, 1159, 1211, 1216,
                      1219, 1221, 1222, 1223, 1224, 1228, 1231))
```


```{r}
ag_tab_03321_00_20_raw <- ApiData12(
  urlToData = "03321",
  ArbstedKomm = knr, 
  ContentsCode = "Sysselsatte",
  Bokommuen = knr,
  Tid = as.character(2000:2020)
  )
```

```{r}
names(ag_tab_03321_00_20_raw)
```

Bruker man ApiData() får man 

```{r}
ag_tab_03321_00_20_raw_B <- ApiData(
  urlToData = "03321",
  ArbstedKomm = knr, 
  ContentsCode = "Sysselsatte",
  Bokommuen = knr,
  Tid = as.character(2000:2020)
  )
```

```{r}
names(ag_tab_03321_00_20_raw_B)
```

```{r}
names(ag_tab_03321_00_20_raw_B[[1]])
```

```{r}
names(ag_tab_03321_00_20_raw_B[[2]])
```

